version: '3.8'
services:
  broker:
    image: apache/kafka:3.7.0 # Using a specific stable version is good practice
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1 # Default partitions for new topics

      # KRaft configuration
      KAFKA_CLUSTER_ID: "YOUR_KAFKA_CLUSTER_ID_UUID" # !!! IMPORTANT: Replace with a generated UUID !!!
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      # Ensure advertised hostname matches container name for inter-container communication
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS_CONTROLLER_HOST_NAME: broker
      KAFKA_LISTENERS_CONTROLLER_PORT: 29093
    command:
      - bash
      - -c
      - |
        if [ ! -f /tmp/kraft-combined-logs/meta.properties ]; then
          kafka-storage.sh format -t "$$KAFKA_CLUSTER_ID" -c config/kraft/server.properties
        fi;
        exec kafka-server-start.sh config/kraft/server.properties
    volumes:
      # Optional: Mount a custom server.properties if needed
      - ./config/kafka/server.properties:/opt/kafka/config/kraft/server.properties:ro

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092 # Use the internal Docker network name and port
      KAFKA_CLUSTERS_0_PROPERTIES_0_KEY: ssl.endpoint.identification.algorithm
      KAFKA_CLUSTERS_0_PROPERTIES_0_VALUE: ""
      # KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181 # Only if using ZooKeeper-based Kafka
    depends_on:
      - broker